### ISSUE TITLE
There must be a varible in setting for AJAX calls

### ISSUE THREAD

**Issue by DanishAbsar** [CleitonDeLima/django-login-required-middleware#10]
Hi @CleitonDeLima, 

I think there also be a variable in a setting that helps to handle the ajax call either be enable or disable.

In the case of ajax based login and signup, it fails.

Thanks

**Comment by CleitonDeLima** [comment]
Hi @DanishAbsar,

What's your idea for this feature?
Could you give me an example?

**Comment by DanishAbsar** [comment]
Sure,

Let's say I have to make login or register or both through an AJAX call, then it blocks that call as AJAX call is blocked by default (if a user isn't logged in).

Thanks

**Comment by CleitonDeLima** [comment]
I understood,

If you make ajax calls but want to disregard some urls then that doesn't work, correct?
If you can create a PR I appreciate it, we can see it together. :+1:

**Comment by DanishAbsar** [comment]
disregards URL is not a point of worry. if user asks the system to allow ajax call then, it allows ajax only for those URL which is present in LOGIN_REQUIRED_IGNORE_PATHS, rest will be blocked.

will provide a PR.
