### ISSUE TITLE
Allow urls with token

### ISSUE THREAD

**Issue by raj1rana** [CleitonDeLima/django-login-required-middleware#13]
Urls like :- `/users/^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',`  that are use for email verification are not working with the package i have enabled the View and Path in my settings but does not seems to work

**Comment by CleitonDeLima** [comment]
Hi @raj1rana,

Show me your settings so I can test this setting.
