### ISSUE TITLE
Middleware doesn’t appear to be compatible with django flatpages

### ISSUE THREAD

**Issue by andylolz** [CleitonDeLima/django-login-required-middleware#31]
This middleware doesn’t redirect to login if the response is a 404.

I think this means the middleware is not compatible with [django flatpages](https://docs.djangoproject.com/en/3.1/ref/contrib/flatpages/) – specifically the [FlatpageFallbackMiddleware](https://docs.djangoproject.com/en/3.1/ref/contrib/flatpages/#django.contrib.flatpages.middleware.FlatpageFallbackMiddleware), which relies on intercepting 404 responses. If someone uses that app with this, pages that should be behind a login may accidentally be exposed.

It could _arguably_ also be considered a security issue, since responding to some requests with a 404 leaks information about which routes behind the login are valid.

---

EDIT: Sorry, I should add: Many thanks for making this! It is great. I’ve sent a PR in an attempt to fix this issue.

**Comment by CleitonDeLima** [comment]
Hi @andylolz 

Thank you for your contribution! I didn't really think about it. Soon I will check your PR and get the token for the tests to pass.
;)

**Comment by andylolz** [comment]
Excellent – thank you!
