### ISSUE TITLE
LOGIN_REQUIRED_IGNORE_PATHS not working properly 

### ISSUE THREAD

**Issue by bgeneto** [CleitonDeLima/django-login-required-middleware#8]
I have the following simple setup:

```
LOGIN_REQUIRED_IGNORE_PATHS = [
    r'accounts/login/$',
    r'accounts/signup/$',
]
```

While trying to access the following URL directly: 

http://127.0.0.1:8000/accounts/signup/

Instead of the signup page I'm redirected to: 

http://127.0.0.1:8000/accounts/login/?next=/accounts/signup/

LOGIN_REQUIRED_IGNORE_VIEW_NAMES although works correctly. 

But I prefer to use regex in order to allow password_reset pages (like Django's password_reset_done, password_reset_complete, password_reset_confirm etc...). The following also does not work: 

`LOGIN_REQUIRED_IGNORE_PATHS = [
    r'accounts/password_reset.*/$'
]`

Conclusion: Using Django 2.2 LOGIN_REQUIRED_IGNORE_PATHS does NOT work at all...

**Comment by CleitonDeLima** [comment]
Truth,

Readme is out of date, try like this (the `/` in the early url):

```python
LOGIN_REQUIRED_IGNORE_PATHS = [
    r'/accounts/signup/$',
]
```

For `LOGIN_REQUIRED_IGNORE_PATHS`, by default `settings.LOGIN_URL` is used.

If you want you can make a PR of it, I appreciate it :)
